[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "Agriculture DETR"
version = "0.0.1"

dependencies = [
    "torch==2.4.1",
    "torchvision"
]

[tool.hatch.build.targets.wheel]
packages = [ "*" ]
